### ISSUE TITLE
Uhm

### ISSUE THREAD

**Issue by macedonga** [rpxs/kcss#4]
Please don't tell me that you have to create an html file for all the requests you get. You should create them dynamically

**Comment by rpxs** [comment]
I agree, and I'm currently making an express site. However, this does not give you permission to raid a Discord server with webhooks. The immaturity you displayed here is beyond my comprehension. 
![image](https://user-images.githubusercontent.com/66899904/103372302-e142e080-4a8e-11eb-8c57-e8dadd12a833.png)
You are in no position to make comments about this repository as of now. Trying to raid the Discord server shows that you lack basic common sense and courtesy that all humans should have.
